package bank.online.entities;

public enum ERole {
	ROLE_CLIENT,
    ROLE_GESTIONNAIRE_CLIENTELE,
    ROLE_CONSEILLER_CLIENTELE,
    ROLE_MEMBRE_DIRECTOIRE,
    ROLE_PERSONNEL_FINANCIER,
    ROLE_PERSONNEL_RH,
    ROLE_EMPLOYE_CAP
}